services:
  notedoc:
    image: notedoc:latest
    depends_on:
      - db
      - redis
    environment:
      APP_URL: 'http://localhost:3000'
      APP_SECRET: 'your-super-secret-key-at-least-32-characters-long'
      DATABASE_URL: 'postgresql://notedoc:notedoc123@db:5432/notedoc?schema=public'
      REDIS_URL: 'redis://redis:6379'
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - notedoc_data:/app/data/storage

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: notedoc
      POSTGRES_USER: notedoc
      POSTGRES_PASSWORD: notedoc123
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  notedoc_data:
  db_data:
  redis_data:
