services:
  notedoc:
    image: notedoc/notedoc:latest
    depends_on:
      - db
      - redis
    environment:
      APP_URL: 'http://localhost:3000'
      APP_SECRET: 'REPLACE_WITH_LONG_SECRET'
      DATABASE_URL: 'postgresql://notedoc:STRONG_DB_PASSWORD@db:5432/notedoc?schema=public'
      REDIS_URL: 'redis://redis:6379'
    ports:
      - "3001:3000"
    restart: unless-stopped
    volumes:
      - notedoc:/app/data/storage

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: notedoc
      POSTGRES_USER: notedoc
      POSTGRES_PASSWORD: STRONG_DB_PASSWORD
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  notedoc:
  db_data:
  redis_data:
